"use client";

import Link from "next/link";
import { useCart } from "@/components/CartProvider";
import { formatNaira } from "@/lib/format";

export default function CartPage() {
  const { items, total, count, remove, setQuantity } = useCart();
  return <main className="mx-auto min-h-screen max-w-5xl px-6 py-12"><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Your basket</p><h1 className="mt-2 text-4xl font-black text-gray-950">Cart <span className="text-gray-400">({count})</span></h1>{!items.length ? <div className="mt-10 rounded-2xl border border-dashed border-gray-300 bg-white p-16 text-center"><p className="text-gray-500">Your cart is empty.</p><Link href="/gadgets" className="mt-5 inline-block rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Browse marketplace</Link></div> : <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_320px]"><div className="space-y-4">{items.map((item) => <div key={item.id} className="flex gap-4 rounded-2xl border border-gray-200 bg-white p-4"><div className="h-24 w-24 shrink-0 rounded-xl bg-gray-100 bg-cover bg-center" style={{ backgroundImage: item.images[0] ? `url(${item.images[0].url})` : undefined }} /><div className="min-w-0 flex-1"><h2 className="font-black text-gray-950">{item.title}</h2><p className="mt-1 font-bold">{formatNaira(item.price)}</p><div className="mt-3 flex items-center gap-3"><button type="button" onClick={() => setQuantity(item.id, item.cartQuantity - 1)} className="h-8 w-8 rounded-lg border">-</button><span>{item.cartQuantity}</span><button type="button" onClick={() => setQuantity(item.id, item.cartQuantity + 1)} className="h-8 w-8 rounded-lg border">+</button><button type="button" onClick={() => remove(item.id)} className="ml-3 text-sm font-bold text-red-600">Remove</button></div></div></div>)}</div><aside className="h-fit rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-black">Order summary</h2><div className="mt-6 flex justify-between border-t pt-4"><span>Total</span><strong>{formatNaira(total)}</strong></div><Link href="/checkout" className="mt-6 block rounded-xl bg-blue-600 px-5 py-3 text-center font-bold text-white">Proceed to checkout</Link><Link href="/gadgets" className="mt-3 block text-center text-sm font-bold text-blue-600">Continue shopping</Link></aside></div>}</main>;
}
